on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - run: gh workflow --repo cndoit18/demo-chart-repo run .github/workflows/release.yml -f component=frobnitz
        env:
          GITHUB_TOKEN: ${{ secrets.REMOTE_TOKEN }}
